# Generated by Django 4.1.6 on 2023-02-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_name', models.CharField(max_length=64)),
                ('nft_token', models.CharField(max_length=128, blank=True)),
                ('nft_image', models.ImageField(upload_to='img')),
                ('nft_owner_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wallet', default=1)),
            ],
        ),
    ]
