# Generated by Django 4.1.6 on 2023-02-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='nft_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='nft',
            old_name='nft_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nft',
            old_name='nft_owner_wallet',
            new_name='owner_wallet_nft',
        ),
        migrations.RenameField(
            model_name='nft',
            old_name='nft_token',
            new_name='token',
        ),
        migrations.AddField(
            model_name='nft',
            name='description',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
