# Generated by Django 4.1.6 on 2023-02-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_nft_image_nft_image_rename_nft_name_nft_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='name',
            new_name='nft_name',
        ),
    ]
