# Generated by Django 4.1.6 on 2023-02-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_wallet_telegram_user_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='cryptocurrency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.token'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
