# Generated by Django 4.1.6 on 2023-02-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='nft_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
