# Generated by Django 4.1.6 on 2023-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_nft_description_alter_nft_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='telegram_image_id',
            field=models.CharField(blank=True, max_length=196, null=True),
        ),
    ]
