# Generated by Django 4.1.6 on 2023-02-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_nft_telegram_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='telegram_image_id',
        ),
    ]
