# Generated by Django 4.1.6 on 2023-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
