# Generated by Django 4.1.6 on 2023-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegramuser_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='selected_date',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
